const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://bit.ly/TRIBE_UNIABUJA";
global.website=process.env.GURL || "https://bit.ly/TRIBE_UNIABUJA" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2349069060810";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "Tribe Internal Bot" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Tribe Bot",
  packname: process.env.PACK_NAME || "🎮",
  botname : process.env.BOT_NAME  || "Tribe",
  ownername:process.env.OWNER_NAME|| "TribeUNIABUJA",

  sessionName:process.env.SESSION_ID || "SUHAIL_12_47_10_04_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTQ0LFxuICAgICAgICAxMDYsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMjA5LFxuICAgICAgICA5LFxuICAgICAgICA5LFxuICAgICAgICAxNSxcbiAgICAgICAgMTA3LFxuICAgICAgICAxMzAsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMTQ0LFxuICAgICAgICAyMzksXG4gICAgICAgIDMzLFxuICAgICAgICA0MCxcbiAgICAgICAgODMsXG4gICAgICAgIDk3LFxuICAgICAgICAyMTcsXG4gICAgICAgIDM5LFxuICAgICAgICAxODgsXG4gICAgICAgIDY2LFxuICAgICAgICAxNTUsXG4gICAgICAgIDE2NCxcbiAgICAgICAgNjksXG4gICAgICAgIDIxMyxcbiAgICAgICAgMjA0LFxuICAgICAgICAxMjYsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMjE4LFxuICAgICAgICA5MCxcbiAgICAgICAgMzYsXG4gICAgICAgIDExNSxcbiAgICAgICAgODBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTI5LFxuICAgICAgICA0NyxcbiAgICAgICAgOTIsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTg4LFxuICAgICAgICA2MSxcbiAgICAgICAgMTg5LFxuICAgICAgICAyNSxcbiAgICAgICAgMTIwLFxuICAgICAgICAyMyxcbiAgICAgICAgMTA2LFxuICAgICAgICAyMTUsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMTI4LFxuICAgICAgICA1OCxcbiAgICAgICAgNDEsXG4gICAgICAgIDU4LFxuICAgICAgICAxOTMsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMjU1LFxuICAgICAgICA0NyxcbiAgICAgICAgMTA3LFxuICAgICAgICAzNyxcbiAgICAgICAgODYsXG4gICAgICAgIDE1MixcbiAgICAgICAgOTksXG4gICAgICAgIDU2LFxuICAgICAgICAyMjIsXG4gICAgICAgIDE5NSxcbiAgICAgICAgMjI4LFxuICAgICAgICA2NCxcbiAgICAgICAgNDFcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTQ4LFxuICAgICAgICAyNDMsXG4gICAgICAgIDk1LFxuICAgICAgICAyNDcsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTYyLFxuICAgICAgICAxMDgsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMjI0LFxuICAgICAgICAzNCxcbiAgICAgICAgMTM4LFxuICAgICAgICA1OCxcbiAgICAgICAgMjQ2LFxuICAgICAgICA3NSxcbiAgICAgICAgMTQ2LFxuICAgICAgICA2MyxcbiAgICAgICAgMjMwLFxuICAgICAgICAxMTIsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTMsXG4gICAgICAgIDEwOCxcbiAgICAgICAgODUsXG4gICAgICAgIDE2LFxuICAgICAgICAyMzcsXG4gICAgICAgIDE5NixcbiAgICAgICAgMTUwLFxuICAgICAgICAyNTAsXG4gICAgICAgIDEsXG4gICAgICAgIDkyLFxuICAgICAgICAyNTIsXG4gICAgICAgIDEyMlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxODgsXG4gICAgICAgIDgzLFxuICAgICAgICAxNjUsXG4gICAgICAgIDYwLFxuICAgICAgICAyMDQsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMjEsXG4gICAgICAgIDcxLFxuICAgICAgICAyNTQsXG4gICAgICAgIDI3LFxuICAgICAgICAyMyxcbiAgICAgICAgMTczLFxuICAgICAgICA5MSxcbiAgICAgICAgMTMsXG4gICAgICAgIDIxNCxcbiAgICAgICAgNTIsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTg5LFxuICAgICAgICA1OCxcbiAgICAgICAgMjQwLFxuICAgICAgICAyMTksXG4gICAgICAgIDUwLFxuICAgICAgICA2NSxcbiAgICAgICAgMSxcbiAgICAgICAgMTc3LFxuICAgICAgICAxNTAsXG4gICAgICAgIDEyMyxcbiAgICAgICAgNjUsXG4gICAgICAgIDIwLFxuICAgICAgICAxODYsXG4gICAgICAgIDE4LFxuICAgICAgICAyMlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMCxcbiAgICAgICAgMTc1LFxuICAgICAgICAyMjEsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTYzLFxuICAgICAgICAxNjgsXG4gICAgICAgIDc1LFxuICAgICAgICAxNDcsXG4gICAgICAgIDk5LFxuICAgICAgICAyMDQsXG4gICAgICAgIDExOSxcbiAgICAgICAgNTQsXG4gICAgICAgIDgxLFxuICAgICAgICAxMjEsXG4gICAgICAgIDI0OCxcbiAgICAgICAgNixcbiAgICAgICAgNDksXG4gICAgICAgIDg3LFxuICAgICAgICA0NCxcbiAgICAgICAgMzcsXG4gICAgICAgIDYyLFxuICAgICAgICAyNDIsXG4gICAgICAgIDE5LFxuICAgICAgICAyMDAsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTY1LFxuICAgICAgICAxMjksXG4gICAgICAgIDExLFxuICAgICAgICAxNyxcbiAgICAgICAgNjIsXG4gICAgICAgIDE5LFxuICAgICAgICAxMDRcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODcsXG4gICAgICAgIDQsXG4gICAgICAgIDIyNixcbiAgICAgICAgMTIyLFxuICAgICAgICAxMjAsXG4gICAgICAgIDM4LFxuICAgICAgICAxMTYsXG4gICAgICAgIDcsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTEsXG4gICAgICAgIDU4LFxuICAgICAgICAxNzIsXG4gICAgICAgIDUyLFxuICAgICAgICA2LFxuICAgICAgICAxMTYsXG4gICAgICAgIDE5NixcbiAgICAgICAgNjcsXG4gICAgICAgIDE2MyxcbiAgICAgICAgMzYsXG4gICAgICAgIDc4LFxuICAgICAgICAxMCxcbiAgICAgICAgMTE5LFxuICAgICAgICAyMjAsXG4gICAgICAgIDIzMSxcbiAgICAgICAgNDUsXG4gICAgICAgIDM4LFxuICAgICAgICAxMjIsXG4gICAgICAgIDIzLFxuICAgICAgICAxOSxcbiAgICAgICAgMTE5LFxuICAgICAgICAyNTUsXG4gICAgICAgIDkwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDgwLFxuICAgICAgICAgIDE4NixcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgMjI5LFxuICAgICAgICAgIDEwNixcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgMjAxLFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICA1MCxcbiAgICAgICAgICAzMSxcbiAgICAgICAgICAxMjQsXG4gICAgICAgICAgMzgsXG4gICAgICAgICAgMTEwLFxuICAgICAgICAgIDI1MCxcbiAgICAgICAgICAyNSxcbiAgICAgICAgICA4NCxcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgNjEsXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDIzNCxcbiAgICAgICAgICAxMTEsXG4gICAgICAgICAgMTc5LFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICAyMDMsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDE0NixcbiAgICAgICAgICA2OCxcbiAgICAgICAgICA4MFxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxMTksXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgMjUxLFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICAxMjEsXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgNzAsXG4gICAgICAgICAgODMsXG4gICAgICAgICAgNDYsXG4gICAgICAgICAgMjE4LFxuICAgICAgICAgIDE3LFxuICAgICAgICAgIDIzOSxcbiAgICAgICAgICA4NCxcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgMjMyLFxuICAgICAgICAgIDE5NCxcbiAgICAgICAgICA3NyxcbiAgICAgICAgICAxMzcsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDIyMyxcbiAgICAgICAgICAxOTksXG4gICAgICAgICAgMCxcbiAgICAgICAgICAxODgsXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDE1NSxcbiAgICAgICAgICAxNTIsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDExNixcbiAgICAgICAgICA4OCxcbiAgICAgICAgICA0OFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDc0LFxuICAgICAgICAxNTUsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTg5LFxuICAgICAgICAyNDUsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMjQzLFxuICAgICAgICAxNzMsXG4gICAgICAgIDk0LFxuICAgICAgICA0OSxcbiAgICAgICAgOCxcbiAgICAgICAgMjMsXG4gICAgICAgIDY0LFxuICAgICAgICAyNTUsXG4gICAgICAgIDIxNixcbiAgICAgICAgMjE5LFxuICAgICAgICA2MixcbiAgICAgICAgMTE0LFxuICAgICAgICAxMDAsXG4gICAgICAgIDIwMixcbiAgICAgICAgMjI4LFxuICAgICAgICAxNjcsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMTc2LFxuICAgICAgICAyNTEsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMTI2LFxuICAgICAgICAxNDQsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMjA4LFxuICAgICAgICAyMTcsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMjA1LFxuICAgICAgICAyMTUsXG4gICAgICAgIDIzMyxcbiAgICAgICAgNjEsXG4gICAgICAgIDU0LFxuICAgICAgICA5MCxcbiAgICAgICAgMjQxLFxuICAgICAgICAxODksXG4gICAgICAgIDIzNCxcbiAgICAgICAgMTE4LFxuICAgICAgICAyMjksXG4gICAgICAgIDE4OSxcbiAgICAgICAgNTQsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTI1LFxuICAgICAgICAxMzMsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMjA2LFxuICAgICAgICAxMTYsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMTMxLFxuICAgICAgICAyMzIsXG4gICAgICAgIDE1NSxcbiAgICAgICAgODcsXG4gICAgICAgIDEyMixcbiAgICAgICAgMjM5LFxuICAgICAgICAyNTQsXG4gICAgICAgIDIxNCxcbiAgICAgICAgNyxcbiAgICAgICAgMTU4LFxuICAgICAgICAyMjMsXG4gICAgICAgIDJcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDEyMSxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJtRmxJK2I2K3hGbDhiYlZWcFFMd2YyVkp2aUdPNDdlUkw2MlAyMFlJdUZZPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDkwNjkwNjA4MTBAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkI3M0QzOUFCNENEMENFN0FGQTEyRDI0MjhBOTc5M0IzXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyODA0NjAxOVxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJwMGRtQ3hNOFN4ZXNPNER5c2lPOWNRXCIsXG4gIFwicGhvbmVJZFwiOiBcImI0NzdhY2M2LTY2NTEtNDY3NC1hZDVkLTViM2MwNDZlMWRlYVwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA1MyxcbiAgICAgIDI0NyxcbiAgICAgIDI0NyxcbiAgICAgIDY5LFxuICAgICAgNzAsXG4gICAgICA2NixcbiAgICAgIDE0MCxcbiAgICAgIDE0LFxuICAgICAgMTM5LFxuICAgICAgOTIsXG4gICAgICAyNDYsXG4gICAgICAxMDcsXG4gICAgICA5MCxcbiAgICAgIDIwMixcbiAgICAgIDExLFxuICAgICAgNzcsXG4gICAgICAzNCxcbiAgICAgIDE2MyxcbiAgICAgIDIzMyxcbiAgICAgIDE5MVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IGZhbHNlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjQ3LFxuICAgICAgMTQzLFxuICAgICAgMjksXG4gICAgICAyMjMsXG4gICAgICA4NSxcbiAgICAgIDIwNCxcbiAgICAgIDEyOSxcbiAgICAgIDU3LFxuICAgICAgMTYwLFxuICAgICAgOTksXG4gICAgICAyNDAsXG4gICAgICAyMTUsXG4gICAgICAxOTEsXG4gICAgICAxODIsXG4gICAgICAxNDMsXG4gICAgICAyMzksXG4gICAgICA1MyxcbiAgICAgIDE0MixcbiAgICAgIDE2NixcbiAgICAgIDI0XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDTFhJZ3VFR0VMakgvN2NHR0FVZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJ5anAxcmFmV2cxaHBQL1gzbHhEZEZZNmNoRVRPUjFoVlNyRlNwNjBZZlRzPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcImZEeGMvekdrZ2JTNzZJdDZQMXNzYjVoQkZOS0YyUzBJTzdJa28xQ1hsOEVHbFZybkp4azRKSHlaMHpmR2xqelhIeENpREkyTGNwejNNa1pJNW9yRkFBPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIkRhcXRsMVJpcVQrVS93d1d2Sk4rWDRKbXlkVi9YZjFkMTZsV3VzTmEySzNqdXNpMTdMMnlCMUUzc1R1N2tNWk1mOEViRlRTM3NIOWFXVUtiWXA1R0RRPT1cIlxuICB9LFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjM0OTA2OTA2MDgxMDoxMUBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibmFtZVwiOiBcIlBsdXNcIixcbiAgICBcImxpZFwiOiBcIjU2ODQ4NTM5NDU1NjU3OjExQGxpZFwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjM0OTA2OTA2MDgxMDoxMUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDIwMixcbiAgICAgICAgICA1OCxcbiAgICAgICAgICAxMTcsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDE2NyxcbiAgICAgICAgICAyMTQsXG4gICAgICAgICAgMTMxLFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDEwNSxcbiAgICAgICAgICA2MyxcbiAgICAgICAgICAyNDUsXG4gICAgICAgICAgMjQ3LFxuICAgICAgICAgIDE1MSxcbiAgICAgICAgICAxNixcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgMjEsXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICAxMzIsXG4gICAgICAgICAgNjgsXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDcxLFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDE3NyxcbiAgICAgICAgICA4MixcbiAgICAgICAgICAxNjcsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDEyNSxcbiAgICAgICAgICA1OVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwic21iYVwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI4MDQ2MDEzLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBQVcxXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBVzAuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCI4dnN0NjJwWVdlSDhkbGNWVm9pUXREQlMrdXlFYStKcFlaUk9YdjdOaXBnPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE4MTQwNzg1MTcsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUFXMS5qc29uIjogIntcImtleURhdGFcIjpcIjFUcVJGaEovb1BtVlVBbkIzamlpR2c1RGxIazBWSGdUUm1IUHNhQjJQTXM9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTgxNDA3ODUxNyxcImN1cnJlbnRJbmRleFwiOjMsXCJkZXZpY2VJbmRleGVzXCI6WzAsMSwyXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBVzIuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJsVXJZSk4rU210d3cwV25ENGxjcHV3a3ZQazBYMGdyTVcvbTdXVDIvenFJPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE4MTQwNzg1MTcsXCJjdXJyZW50SW5kZXhcIjozLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyODA0NTgxMDIxMFwifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
